---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/nyeh/Desktop/fall_2021/NDG/exp1/data/analyses")
#setwd("/koenlab/koendata/EXPT/nd002/across_experiment_analyses")
df = read.csv('memory_measures_data_longgraphs.csv',header = T)
#library(ggsci)
```

```{r package setup, include = TRUE, echo = TRUE}
# Load Libraries
library(afex)
library(emmeans)
library(modelbased)
library(effectsize)
library(ggplot2)
library(PupillometryR)
library(ggpubr)

# knitr options
knitr::opts_chunk$set(echo = FALSE, include = FALSE, message = FALSE)

# ggplot themes.
this_theme <- theme(    
  panel.background    = element_blank() ,            #   control the major gridlines 
  panel.grid.major.y  = element_line() ,             #   suppress the vertical grid lines
  panel.grid.major.x  = element_blank() ,            #   suppress the minor grid lines
  panel.grid.minor    = element_blank() ,            #   add axes
  axis.text           = element_text(size=20, family="Times", colour='black'),   #   tick labels' size, font & color. 
  axis.line.x         = element_line( size=.8),   #   adjust the axis ticks
  axis.line.y         = element_line( size=.8),
  axis.ticks          = element_line( size=.8, colour='black'),   #   axis colors and thickness 
  axis.title.y        = element_text( angle=90, vjust= 1.5, hjust=.47,    
                                      size=20, family="Times"),  
  axis.title.x        = element_text(vjust=-.5, hjust = .505,                    
                                      size=20, family="Times"),                   
  plot.title = element_text (size=20, family="Times", colour='black', face = 'bold'),
  legend.text = element_text(size=20, family="Times"),
  legend.title = element_text(size=20, family="Times", face = 'bold'),
  plot.subtitle = element_text(size=20,  face="bold", color="black")
  )

# Raincloud plot function
make_cloud_plot <- function(df1, df2, dv,memory_measure) {
  plot <- ggplot(data=df1, aes(x = x_location, y = get(dv), fill = study_instruction_condition)) +
    geom_flat_violin(aes(x = .85, fill = study_instruction_condition),
                     position = position_nudge(x = .1, y = 0), 
                     adjust = .7, trim = TRUE, alpha = .3, 
                     colour = NA, show.legend=FALSE) +
    geom_point(aes(x = x_location, y = get(dv), colour = study_instruction_condition),
               position = position_jitter(width = .05, height = 0), 
               size = 4, shape = 20, alpha = .9) +
    geom_boxplot(aes(x = x_location, y = get(dv), fill = study_instruction_condition),
                 outlier.shape = NA, alpha = .5, width = .1, colour = "black", 
                 notch=FALSE, show.legend=FALSE) +
    geom_line(aes(x = x_location, y = model_means, group = 1), 
              data = df2, linetype = "dashed", size=1) +
    geom_errorbar(aes(x = x_location, group = study_instruction_condition, 
                      y = model_means, ymin = CI_low, ymax = CI_high), 
                  data = df2, width = .05, size=1, colour='black') +
    geom_point(aes(x = x_location, y = model_means, group = study_instruction_condition, fill = study_instruction_condition),
               data = df2, 
               shape = 22, size = 3, stroke = 1, color = "black") +
    scale_colour_manual(values = c("#3C5488FF", "#00A087FF"))+
    scale_fill_manual(values = c("#3C5488FF" ,"#00A087FF"))+
#     scale_colour_manual(values = c("#DC0000FF", "#4DBBD5FF", "#00A087FF"))+
#     scale_fill_manual(values = c("#DC0000FF", "#4DBBD5FF", "#00A087FF"))+   
    ggtitle(sc_type) + 
    ylab(memory_measure) +
    xlab("") +
    labs(subtitle = "\n") +
#    scale_x_continuous(expand=c(0, .1),
#                       breaks = (c(.4, .6,.8)),
#                       labels = c("failure", "success","view")) + 
    scale_x_continuous(expand=c(0, .1),
                       breaks = (c(.4, .6)),
                       labels = c("decrease","view")) + 
    this_theme +
#    theme(legend.position="none",
#          legend.title=element_blank(),
#          axis.text.x = element_text(angle = 45, hjust = 1,
#                                     color = c('#DC0000FF','#4DBBD5FF', '#00A087FF')))
                                   #  color = c('#1B9E77','#D95F02', '#7570B3')))
    theme(legend.position="none",
         legend.title=element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1,
                                     color = c('#3C5488FF','#00A087FF')))
  return(plot)
}
# 
# Difference Violin function
#lines 92,93, and 94 need to be adjusted with correct location on y-axis (y variable) and p value to display for corrected hit rates, familiarity estimates, recollection (need to be removed), and source memory.
make_diff_plot <- function(df1, df2) {
  plot <- ggplot(data=df1, aes(x=as.numeric(comparison), y=difference)) +
    geom_violin(aes(x = as.numeric(comparison), group = comparison, color = "grey"),
                position = position_nudge(x = 0, y = 0), adjust = .7, trim = TRUE,
                alpha = .3, colour = "grey", fill = "grey")+
    geom_errorbar(aes(x = as.numeric(comparison), group = comparison,
                      y = Difference, ymin = CI_low, ymax =CI_high),
                  data = df2, colour = "black", width = .1, size=1) +
    geom_point(aes(x =as.numeric(comparison), y = Difference, group = comparison),
               data = df2,
               shape = 18, size= 3.5, color = "black") +
    geom_hline(aes(yintercept=0), linetype='dotted', size=.8) +
    annotate("text", x = 1, y = .05, label = "p < .001", size = 4) +
    annotate("text", x = 2, y = .05, label = "p = .024", size = 4) +
    annotate("text", x = 3, y = .05, label = "p < .001", size = 4) +   
    scale_x_continuous(breaks = c(1,2,3),
                       labels= c("informed - no cue","informed - uninformed","uninformed - no cue")) +
    ylab("Difference scores\n") +
    xlab("") +
    labs(subtitle = '') +
    this_theme +
    theme(legend.position = "None",
          axis.text.x = element_text(angle = 45, hjust = 1))
   return(plot)
}
```

```{r}



```

```{r}
df$study_instruction_condition = as.factor(df$study_instruction_condition)
df$participant = as.factor(df$participant)
nd7_stat= df

library(afex)
library(emmeans)
library(dplyr)
head(nd7_stat)
nd7_stat_neg = nd7_stat %>%filter(valence == "negative", study_instruction_condition != "decrease")%>% 
  droplevels()
#run model
nd7_stat_neg_aov <- aov_ez('participant','corrected_recognition',nd7_stat_neg,
                within=c('study_instruction_condition',"scene_component"),
                anova_table = list(es='pes'))
#nd7_stat_neg_aov
#knitr::kable(nice(nd7_stat_neg_aov))
m_nd7_stat_neg_aov = emmeans(nd7_stat_neg_aov, "scene_component", by = c("study_instruction_condition"))

model = summary(m_nd7_stat_neg_aov)
study_instruction_condition = c("failure", "success","view")
sc = c("objects","background")
# Get the  means and CIs
model_means = model$emmean
model_means = c(model$emmean[1] , model$emmean[4] , model$emmean[5] , model$emmean[2] , model$emmean[3],model$emmean[6])
CI_low = c(model$lower.CL[1] , model$lower.CL[4] , model$lower.CL[5] , model$lower.CL[2] , model$lower.CL[3] , model$lower.CL[6])
CI_high = c(model$upper.CL[1] , model$upper.CL[4] , model$upper.CL[5] , model$upper.CL[2] , model$upper.CL[3] , model$upper.CL[6])
cr_df = data.frame(study_instruction_condition,sc,model_means,CI_low,CI_high )

#summary(pairs(m_nd7_stat_neg_aov), by=NULL, adjust = "none")

cr_df$x_location <- c(.4, .6, .8) # F,S, V
cr_df$x_location <- cr_df$x_location + .1
cr_df_objects = cr_df%>%
  filter(sc == "objects")
cr_df_objects

df2_x_axis = nd7_stat_neg %>%
  mutate(x_location = 
           case_when(study_instruction_condition == "success" ~.6,
                     study_instruction_condition == "failure" ~.4,
                     study_instruction_condition == "view" ~.8))
df2_x_axis = df2_x_axis%>%
  filter(scene_component == "objects")

# Make the plots
sc_type = "Objects"
memory_measure = "Corrected recognition" #
#study_instruction_condition
rain_objects <- make_cloud_plot(df2_x_axis, cr_df_objects,'corrected_recognition',memory_measure)
rain_objects

#backgrounds
cr_df_background = cr_df%>%
  filter(sc == "background")
cr_df_background

  df2_x_axis_bg = nd7_stat_neg %>%
  mutate(x_location = 
           case_when(study_instruction_condition == "success" ~.6,
                     study_instruction_condition == "failure" ~.4,
                     study_instruction_condition == "view" ~.8))
df2_x_axis_bg = df2_x_axis_bg%>%
  filter(scene_component == "background")
# Make the plots
memory_measure = "Corrected recognition" #
sc_type = "Backgrounds"
#study_instruction_condition
rain_bg <- make_cloud_plot(df2_x_axis_bg, cr_df_background,'corrected_recognition',memory_measure)
rain_bg

```

```{r}
diff = df2_x_axis%>%
  mutate(difference = corrected_recognition - df2_x_axis_bg$corrected_recognition,
         EMTO_index = "object_background")

diff <- subset(diff, select = -c(scene_component,corrected_recognition))
diff <- subset(diff, select = -c(corrected_recognition))

 plot_dff <- ggplot(data=diff, aes(x=as.numeric(study_instruction_condition), y=difference)) +
    geom_violin(aes(x = as.numeric(study_instruction_condition), group = study_instruction_condition, color = "grey"),
                position = position_nudge(x = 0, y = 0), adjust = .7, trim = TRUE,
                alpha = .3, colour = "grey", fill = "grey")+
   # geom_errorbar(aes(x = as.numeric(study_instruction_condition), group = study_instruction_condition,
   #                   y = difference, ymin = CI_low, ymax =CI_high),
  #                data = df2, colour = "black", width = .1, size=1) +
  #  geom_point(aes(x =as.numeric(study_instruction_condition), y = difference, group = study_instruction_condition),
  #             data = df2,
  #             shape = 18, size= 3.5, color = "black") +
    geom_hline(aes(yintercept=0), linetype='dotted', size=.8) +
 #   annotate("text", x = 1, y = .05, label = "p < .001", size = 4) +
#    annotate("text", x = 2, y = .05, label = "p = .024", size = 4) +
#    annotate("text", x = 3, y = .05, label = "p < .001", size = 4) +   
    scale_x_continuous(breaks = c(1,2,3),
                       labels= c("view","success","failure")) +
    ylab("Difference scores\n") +
    xlab("") +
    labs(subtitle = '') +
    this_theme +
    theme(legend.position = "None",
          axis.text.x = element_text(angle = 45, hjust = 1))
 
plot_dff


 plot_diff_rain <- ggplot(data=diff, aes(x = x_location, y = difference, fill = study_instruction_condition)) +
    geom_flat_violin(aes(x = 1, fill = study_instruction_condition),
                     position = position_nudge(x = .1, y = 0), 
                     adjust = .7, trim = TRUE, alpha = .3, 
                     colour = NA, show.legend=FALSE) +
    geom_point(aes(x = x_location, y = difference, colour = study_instruction_condition),
               position = position_jitter(width = .05, height = 0), 
               size = 4, shape = 20, alpha = .9) +
    geom_boxplot(aes(x = x_location, y = difference, fill = study_instruction_condition),
                 outlier.shape = NA, alpha = .5, width = .1, colour = "black", 
                 notch=FALSE, show.legend=FALSE) +
 #   geom_line(aes(x = x_location, y = model_means, group = 1), 
  #            data = df2, linetype = "dashed", size=1) +
   # geom_errorbar(aes(x = x_location, group = study_instruction_condition, 
  #                    y = model_means, ymin = CI_low, ymax = CI_high), 
  #                data = df2, width = .05, size=1, colour='black') +
  #  geom_point(aes(x = x_location, y = model_means, group = study_instruction_condition, fill = study_instruction_condition),
  #             data = df2, 
  #             shape = 22, size = 3, stroke = 1, color = "black") +
    scale_colour_brewer(palette = "Dark2") +
    scale_fill_brewer(palette = "Dark2") +
    ggtitle("") + 
    ylab("Index") +
    xlab("") +
    labs(subtitle = "\n") +
    scale_x_continuous(expand=c(0, .1),
                       breaks = (c(.4, .6,.8)),
                       labels = c("view","success","failure")) + 
    this_theme +
    theme(legend.position="none",
          legend.title=element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1,
                                     color = c('#1B9E77','#D95F02', '#7570B3')))
 
plot_diff_rain
```

```{r}
head(nd7_stat)
nd7_stat_reappraisal = nd7_stat %>%filter(valence == "negative", study_instruction_condition %in% c("decrease","view"))%>% 
  droplevels()

nd7_stat_reappraisal_model <- aov_ez('participant','corrected_recognition',nd7_stat_reappraisal,
                within=c('study_instruction_condition',"scene_component"),
                anova_table = list(es='pes'))
#nd7_stat_reappraisal_model
#knitr::kable(nice(nd7_stat_reappraisal_model))

m_nd7_stat_aov = emmeans(nd7_stat_reappraisal_model, "scene_component", by = c("study_instruction_condition"))
model = summary(m_nd7_stat_aov)
model
study_instruction_condition = c("decrease","decrease","view","view")
sc = c("object","background")

model_means = c(model$emmean[1] , model$emmean[4] , model$emmean[3] , model$emmean[4])
CI_low = c(model$lower.CL[1] , model$lower.CL[4] , model$lower.CL[3] , model$lower.CL[4] )
CI_high = c(model$upper.CL[1] , model$upper.CL[4] ,  model$upper.CL[3] , model$upper.CL[4] )
cr_df = data.frame(study_instruction_condition,sc,model_means,CI_low,CI_high )
cr_df
#summary(pairs(m_nd7_stat_neg_aov), by=NULL, adjust = "none")
# Get the modelbased means and standard errors
cr_df$x_location <- c(.4, .6) # view,decrease
cr_df$x_location <- cr_df$x_location + .1
cr_df_objects = cr_df%>%
  filter(sc == "object")
cr_df_objects$x_location[2] = .7

df2_x_axis = nd7_stat_reappraisal %>%
  mutate(x_location = 
           case_when(study_instruction_condition == "decrease" ~.4,
                     study_instruction_condition == "view" ~.6))
df2_x_axis = df2_x_axis%>%
  filter(scene_component == "objects")

# Make the plots
sc_type = "Objects"
memory_measure = "Corrected recognition" #
#study_instruction_condition
rain_objects_reappraisal <- make_cloud_plot(df2_x_axis, cr_df_objects,'corrected_recognition',memory_measure)
rain_objects_reappraisal

#backgrounds
cr_df_background = cr_df%>%
  filter(sc == "background")
cr_df_background
cr_df_background$x_location[1] = .5

  df2_x_axis_bg = nd7_stat_reappraisal %>%
  mutate(x_location = 
           case_when(study_instruction_condition == "decrease" ~.4,
                     study_instruction_condition == "view" ~.6))
df2_x_axis_bg = df2_x_axis_bg%>%
  filter(scene_component == "background")
# Make the plots
sc_type = "Backgrounds"
memory_measure = "Corrected recognition" #
#study_instruction_condition

rain_bg_reappraisal <- make_cloud_plot(df2_x_axis_bg, cr_df_background,'corrected_recognition',memory_measure)
rain_bg_reappraisal
```


```{r}
library(patchwork)
hello = (rain_objects + rain_bg) / plot_diff_rain
hello

plot_emto_sfv = rain_objects + rain_bg 
plot_emto_sfv

plot_emto_DV = rain_objects_reappraisal + rain_bg_reappraisal
plot_emto_DV

```
 
